language: node_js
branches:
  only:
    - development
    - master
node_js:
  - "9.0.0"
install:
  - npm install
script:
  - npm run app:test
services:
  - postgresql
env:
- NODE_ENV=test
cache: 
  - npm install
before_script:
  - npm install -g sequelize-cli@2.8.0
  - psql -c 'create database morerecipes_test;' -U postgres
  - psql -c "create user hamdalah with password 'hamdalah';" -U postgres
  - sequelize db:migrate
after_success: 
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < client/coverage/lcov.info
  - npm run coverage
