language: node_js
branches:
  only:
    - development
    - master
node_js:
  - "9.0.0"
install:
  - npm install
script:
  - npm test
services:
  - postgresql
env:
- NODE_ENV=test
cache: 
  - npm install
before_script:
  - npm install sequelize-cli@2.8.0 -g
  - psql -c 'create database morerecipes_test;' -U postgres
  - psql -c "create user hamdalah with password 'hamdalah';" -U postgres
  - npm run build
  - sequelize db:migrate
after_success: 
  - npm run coverage
