export const
  LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE',
  SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS',
  SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE',
  SET_CURRENT_USER = 'SET_CURRENT_USER',
  REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';
