export const
  LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE',
  SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS',
  SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE',
  SET_CURRENT_USER = 'SET_CURRENT_USER',
  REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER',
  CREATE_RECIPE = 'CREATE_RECIPE',
  CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS',
  CREATE_RECIPE_FAILURE = 'CREATE_RECIPE_FAILURE',
  GET_RECIPE = 'GET_RECIPE',
  GET_RECIPE_SUCCESS = 'GET_RECIPE_SUCCESS',
  GET_RECIPE_FAILURE = 'GET_RECIPE_FAILURE';
